### ISSUE TITLE
Error When Using it Inside Recyclerview

### ISSUE THREAD

**Issue by irfanirawansukirman** [siralam/LoopingViewPager#25]
Hello,

i got problem when using it inside my recyclerview. the error is:

 java.lang.StackOverflowError: stack size 8MB
        at android.view.ViewGroup.jumpDrawablesToCurrentState(ViewGroup.java:7523)
        at android.view.ViewGroup.jumpDrawablesToCurrentState(ViewGroup.java:7527)
        at android.view.ViewGroup.jumpDrawablesToCurrentState(ViewGroup.java:7527)
        at android.view.ViewGroup.jumpDrawablesToCurrentState(ViewGroup.java:7527)
        at android.view.ViewGroup.jumpDrawablesToCurrentState(ViewGroup.java:7527)
        at android.view.ViewGroup.jumpDrawablesToCurrentState(ViewGroup.java:7527)
        at android.view.ViewGroup.jumpDrawablesToCurrentState(ViewGroup.java:7527)
        at android.view.ViewGroup.jumpDrawablesToCurrentState(ViewGroup.java:7527)
        at android.view.ViewGroup.jumpDrawablesToCurrentState(ViewGroup.java:7527)
        at android.view.ViewGroup.jumpDrawablesToCurrentState(ViewGroup.java:7527)
        at android.view.ViewGroup.jumpDrawablesToCurrentState(ViewGroup.java:7527)
        at android.view.ViewGroup.jumpDrawablesToCurrentState(ViewGroup.java:7527)
        at android.view.ViewGroup.jumpDrawablesToCurrentState(ViewGroup.java:7527)
        at android.view.ViewGroup.jumpDrawablesToCurrentState(ViewGroup.java:7527)
        at android.view.ViewGroup.jumpDrawablesToCurrentState(ViewGroup.java:7527)
        at android.view.ViewGroup.jumpDrawablesToCurrentState(ViewGroup.java:7527)
        at android.view.ViewGroup.jumpDrawablesToCurrentState(ViewGroup.java:7527)
        at android.view.ViewGroup.jumpDrawablesToCurrentState(ViewGroup.java:7527)
        at android.view.ViewGroup.jumpDrawablesToCurrentState(ViewGroup.java:7527)
        at android.view.ViewGroup.jumpDrawablesToCurrentState(ViewGroup.java:7527)
        at android.view.ViewGroup.jumpDrawablesToCurrentState(ViewGroup.java:7527)
        at android.view.ViewGroup.jumpDrawablesToCurrentState(ViewGroup.java:7527)
        at android.view.ViewGroup.jumpDrawablesToCurrentState(ViewGroup.java:7527)
        at android.view.ViewGroup.jumpDrawablesToCurrentState(ViewGroup.java:7527)
        at android.view.ViewGroup.jumpDrawablesToCurrentState(ViewGroup.java:7527)
        at android.view.ViewGroup.jumpDrawablesToCurrentState(ViewGroup.java:7527)
        at android.view.ViewGroup.jumpDrawablesToCurrentState(ViewGroup.java:7527)
        at android.view.ViewGroup.jumpDrawablesToCurrentState(ViewGroup.java:7527)
        at android.view.ViewGroup.jumpDrawablesToCurrentState(ViewGroup.java:7527)
        at android.view.ViewGroup.jumpDrawablesToCurrentState(ViewGroup.java:7527)
        at android.view.ViewGroup.jumpDrawablesToCurrentState(ViewGroup.java:7527)
        at android.view.ViewGroup.jumpDrawablesToCurrentState(ViewGroup.java:7527)
        at android.view.ViewGroup.jumpDrawablesToCurrentState(ViewGroup.java:7527)
        at android.view.ViewGroup.jumpDrawablesToCurrentState(ViewGroup.java:7527)
        at android.view.ViewGroup.jumpDrawablesToCurrentState(ViewGroup.java:7527)
        at android.view.ViewGroup.jumpDrawablesToCurrentState(ViewGroup.java:7527)
        at android.view.ViewGroup.jumpDrawablesToCurrentState(ViewGroup.java:7527)
        at android.view.ViewGroup.jumpDrawablesToCurrentState(ViewGroup.java:7527)
        at android.view.ViewGroup.jumpDrawablesToCurrentState(ViewGroup.java:7527)
        at android.view.ViewGroup.jumpDrawablesToCurrentState(ViewGroup.java:7527)
        at android.view.ViewGroup.jumpDrawablesToCurrentState(ViewGroup.java:7527)
        at android.view.ViewGroup.jumpDrawablesToCurrentState(ViewGroup.java:7527)
        at android.view.ViewGroup.jumpDrawablesToCurrentState(ViewGroup.java:7527)
        at android.view.ViewGroup.jumpDrawablesToCurrentState(ViewGroup.java:7527)
        at android.view.ViewGroup.jumpDrawablesToCurrentState(ViewGroup.java:7527)
        at android.view.ViewGroup.jumpDrawablesToCurrentState(ViewGroup.java:7527)
        at android.view.ViewGroup.jumpDrawablesToCurrentState(ViewGroup.java:7527)
        at android.view.ViewGroup.jumpDrawablesToCurrentState(ViewGroup.java:7527)
        at android.view.ViewGroup.jumpDrawablesToCurrentState(ViewGroup.java:7527)
        at android.view.ViewGroup.jumpDrawablesToCurrentState(ViewGroup.java:7527)
        at android.view.ViewGroup.jumpDrawablesToCurrentState(ViewGroup.java:7527)

IDE : Android Studio Stable v3.5.1
Gradle Build : v3.5.1
Gradle Dist : v.5.4.1-all.zip

**Comment by siralam** [comment]
I don't think it is related to the library. But you can paste your full code here so I may be able to help you
